apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: dvn-workshop
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend-prd
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: dvn-workshop
    app.kubernetes.io/managed-by: kustomize
    environment: prd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/instance: frontend-prd
