apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dvn-workshop
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend-prd
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: dvn-workshop
    app.kubernetes.io/managed-by: kustomize
    environment: prd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: frontend-prd
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
