apiVersion: v1
kind: Namespace
metadata:
  name: dvn-workshop
  labels:
    app.kubernetes.io/name: dvn-workshop
    app.kubernetes.io/instance: dvn-workshop-prd
    app.kubernetes.io/part-of: dvn-workshop
    app.kubernetes.io/managed-by: kustomize
    environment: prd
